dist: trusty

language: node_js

node_js:
- 10

branches:
  only:
  - master
  - develop

cache:
  directories:
  - node_modules

jobs:
  include:

    - stage: lint
      script: npm run tslint

    - stage: build
      script: npm run build

    - stage: test
      script: npm run test